# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-06-30 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_auto_20160728_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitebranding',
            old_name='site_logo',
            new_name='site_banner_image',
        ),
        migrations.AlterField(
            model_name='footerlinksrelatedlink',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_links', to='utils.FooterLinks'),
        ),
        migrations.AlterField(
            model_name='sitebranding',
            name='banner_colour',
            field=models.CharField(choices=[('5790D4', 'Blue'), ('56CF8C', 'Green'), ('925914', 'Rusty Red/Orange'), ('5A6978', 'Grey'), ('ffffff', 'None')], default='ffffff', help_text='Pick a colour', max_length=6),
        ),
    ]
